from __future__ import annotations

import uuid
from datetime import date
from typing import Optional, Protocol, Sequence

from backend.domain.gamification.entities import (
    DailyFocusAggregate,
    GamificationEvent,
    UserGamificationProfile,
)


class GamificationRepository(Protocol):
    # ── Profile ──
    async def get_profile(self) -> UserGamificationProfile | None: ...
    async def create_profile(self) -> UserGamificationProfile: ...
    async def lock_profile(self) -> UserGamificationProfile | None: ...
    async def update_profile(self, profile: UserGamificationProfile) -> UserGamificationProfile: ...

    # ── Daily aggregate ──
    async def get_aggregate(self, focus_date: date) -> DailyFocusAggregate | None: ...
    async def lock_aggregate(self, focus_date: date) -> DailyFocusAggregate | None: ...
    async def create_aggregate(self, focus_date: date) -> DailyFocusAggregate: ...
    async def update_aggregate(self, aggregate: DailyFocusAggregate) -> DailyFocusAggregate: ...
    async def list_aggregates(self, since: date, until: date) -> Sequence[DailyFocusAggregate]: ...

    # ── Events ──
    async def create_event(self, event: GamificationEvent) -> GamificationEvent: ...
    async def get_session_reward_event(self, session_id: uuid.UUID) -> GamificationEvent | None: ...

    # ── Active focus room ──
    async def get_active_focus_room_id(self) -> Optional[uuid.UUID]: ...
    async def set_active_focus_room_id(self, room_id: Optional[uuid.UUID]) -> None: ...

    # ── Sessions by day ──
    async def get_sessions_by_day_and_statuses(
        self, day: date, statuses: list[str]
    ) -> Sequence: ...
