from __future__ import annotations

import uuid
from typing import Protocol, Sequence

from backend.domain.chat.entities import ChatThread, ChatMessage


class ChatRepository(Protocol):
    # Thread operations
    async def create_thread(self, thread: ChatThread) -> ChatThread: ...
    async def get_thread(self, thread_id: uuid.UUID) -> ChatThread | None: ...
    async def list_threads(
        self, user_id: uuid.UUID, *, limit: int = 20, offset: int = 0
    ) -> tuple[int | None, Sequence[ChatThread]]: ...
    async def update_thread(self, thread: ChatThread) -> ChatThread: ...
    async def delete_thread(self, thread_id: uuid.UUID) -> None: ...

    # Message operations
    async def create_message(self, message: ChatMessage) -> ChatMessage: ...
    async def list_messages(
        self, thread_id: uuid.UUID, *, limit: int = 50, offset: int = 0
    ) -> tuple[int | None, Sequence[ChatMessage]]: ...
    async def get_thread_messages(self, thread_id: uuid.UUID) -> Sequence[ChatMessage]: ...
