from __future__ import annotations

from typing import Protocol, Optional
import uuid

from backend.domain.users.entities import User


class UserRepository(Protocol):
    async def create(self, user: User) -> User: ...
    async def get_by_id(self, user_id: uuid.UUID) -> Optional[User]: ...
    async def get_by_supabase_user_id(self, supabase_user_id: uuid.UUID) -> Optional[User]: ...
    async def update(self, user: User) -> User: ...
    async def mark_onboarding_completed(self, user_id: uuid.UUID) -> bool: ...
