from __future__ import annotations

import uuid
from typing import Protocol, Sequence

from backend.domain.focus.entities import (
    FocusSession,
    ShopItem,
    UserActiveItem,
    UserBalance,
    UserShopItem,
)


class FocusRepository(Protocol):
    async def list_shop_items_with_owned_ids(self) -> tuple[Sequence[ShopItem], set[uuid.UUID]]: ...
    async def get_shop_item(self, item_id: uuid.UUID) -> ShopItem | None: ...
    async def get_user_shop_item(self, item_id: uuid.UUID) -> UserShopItem | None: ...

    async def get_balance(self) -> UserBalance | None: ...
    async def lock_balance(self) -> UserBalance | None: ...
    async def create_balance(self, coins: int) -> UserBalance: ...
    async def update_balance(self, balance: UserBalance) -> UserBalance: ...

    async def create_user_shop_item(self, item_id: uuid.UUID) -> UserShopItem: ...

    async def create_focus_session(self, session: FocusSession) -> FocusSession: ...
    async def get_focus_session(self, session_id: uuid.UUID) -> FocusSession | None: ...
    async def update_focus_session(self, session: FocusSession) -> FocusSession: ...
    async def list_sessions(
        self, *, limit: int = 50, offset: int = 0
    ) -> Sequence[FocusSession]: ...

    async def get_task_focus_times(
        self, user_id: uuid.UUID, task_ids: list[uuid.UUID]
    ) -> dict[uuid.UUID, int]: ...

    async def get_active_items(self) -> Sequence[UserActiveItem]: ...
    async def set_active_item(self, category: str, item_id: uuid.UUID) -> UserActiveItem: ...
    async def remove_active_item(self, category: str) -> None: ...
